name: Build viewer

on:
  workflow_dispatch:
    inputs:
      operating_system:
        required: true
        type: choice
        description: Operating system
        options:
        - macos-11
      address_size:
        required: true
        type: choice
        description: Address size
        options:
        - 64
        - 32
        default: 64
      build_config:
        required: true
        description: Build configuration
        default: 'ReleaseFS'
      viewer_channel:
        required: true
        description: Viewer channel
        default: 'Betax64'
      grid:
        required: true
        type: choice
        description: Grid
        options:
        - secondlife
        - opensim

env:
  AUTOBUILD_INSTALLABLE_CACHE: ${{github.workspace}}/dep/packages
  AUTOBUILD_VARIABLES_FILE: ${{github.workspace}}/dep/build-variables/variables
  ADDRESS_SIZE: ${{ github.event.inputs.address_size }}
  BUILD_CONFIG: ${{ github.event.inputs.build_config }}
  VIEWER_CHANNEL: ${{ github.event.inputs.viewer_channel }}

jobs:
  build:
    runs-on: ${{ github.event.inputs.operating_system }}

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check out autobuild
      uses: actions/checkout@v2
      with:
        repository: KittyBarnett/fs-autobuild
        ref: main
        path: 'dep/autobuild'

    - name: Check out build-variables
      uses: actions/checkout@v2
      with:
        repository: KittyBarnett/fs-build-variables
        ref: main
        path: 'dep/build-variables'

    - name: Check out action-scp
      uses: actions/checkout@v2
      with:
        repository: CatznipViewer/action-scp
        ref: main
        path: 'dep/action-scp'

    - name: Set environment variables
      run: |
        echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        echo "DEPENDENCIES_SRC_PATH=/dependencies/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        echo "ARTIFACT_DST_PATH=/artifacts/${GITHUB_REPOSITORY#*/}/" >> $GITHUB_ENV
      shell: bash

    - name: Download private packages
      uses: ./dep/action-scp
      with:
        key: ${{ secrets.SCP_KEY }}
        source_host: ${{ secrets.SCP_HOST }}
        source_username: ${{ secrets.SCP_USER }}
        source_file: ${{ env.DEPENDENCIES_SRC_PATH }}/packages/*
        destination_file: './dep/packages/'

    - name: Install autobuild
      run: pip3 install git+https://github.com/Nicky-D/autobuild@main_nd

    - name: Run autobuild configure (Mac)
      if: runner.os == 'macOS'
      run: autobuild configure --verbose -A ${{ env.ADDRESS_SIZE }} -c ${{ env.BUILD_CONFIG }} -- ${{ github.event.inputs.grid == 'secondlife' && '-DHAVOK_TPV=true --no-opensim' || '-DHAVOK_TPV=false --opensim' }} --package --chan "${{ env.VIEWER_CHANNEL }}"

    - name: Run autobuild build
      run: autobuild build -A ${{ env.ADDRESS_SIZE }} -c ${{ env.BUILD_CONFIG }} --no-configure

    - name: Create artifact (Mac)
      if: runner.os == 'macOS'
      run: |
        tar -cvzf ./"${VIEWER_CHANNEL}-$(cat ./indra/newview/VIEWER_VERSION.txt).${AUTOBUILD_BUILD_ID}-${RUNNER_OS}${ADDRESS_SIZE}-${{github.event.inputs.grid}}.tar.gz" ./build-darwin-x86_64/newview/*.dmg
      shell: bash

    - name: Publish artifact
      uses: ./dep/action-scp
      with:
        key: ${{ secrets.SCP_KEY }}
        source_file: ./*.tar.gz
        destination_host: ${{ secrets.SCP_HOST }}
        destination_username: ${{ secrets.SCP_USER }}
        destination_file: ${{ env.ARTIFACT_DST_PATH }}
